### PR TITLE
rc3

### PR DESCRIPTION
**Pull request by utka**

### CODE REVIEW

**Comment by duderino** [comment]
/hold while we figure out if there is an additional PR we want to get into this

@mandarjog

**Comment by duderino** [comment]
/lgtm

We were considering getting https://github.com/istio/istio/pull/12340 into rc3 but since @rshriram put a hold on that we're going to move forward with rc3 without it.

**Comment by rshriram** [comment]
Can we wait until https://github.com/istio/istio/pull/12346 merges? this is a very big issue that several independent folks testing with multicluster have encountered..

**Comment by rshriram** [comment]
So, https://github.com/istio/istio/pull/12304 is passing tests and there is a flag guard to enable memory hog.. Also https://github.com/istio/istio/pull/12340 occurs only when #12304 is in effect.

**Comment by duderino** [comment]
@rshriram https://github.com/istio/istio/pull/11522 was merged 28 days ago, so rc3 will not regress on this since rc2.  I think this is a case of if you miss the train you catch the next one. 

Same thing with the others.  They aren't regressions from rc2.  So let's get rc3 out now and we can create rc4 on Monday if we want

**Pull request merged**
